### ISSUE TITLE
Error with linkml in `sssom validate`

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/sssom-py#73] opened 2021-06-24 18:59 UTC
I'm working on exporting Biomappings to SSSOM (https://github.com/biomappings/biomappings/pull/45) but before I'm done, I want to use the `sssom validate` command to check my TSV is properly formatted. Unfortunately, it's causing the following error due to upstream issues in `linkml`:

```python-traceback
(indra) cthoyt@galvac ~/d/biomappings> sssom validate docs/_data/biomappings.sssom.tsv 
Traceback (most recent call last):
  File "/Users/cthoyt/.virtualenvs/indra/bin/sssom", line 33, in <module>
    sys.exit(load_entry_point('sssom', 'console_scripts', 'sssom')())
  File "/Users/cthoyt/.virtualenvs/indra/bin/sssom", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/cthoyt/dev/sssom-py/sssom/__init__.py", line 1, in <module>
    from .util import (
  File "/Users/cthoyt/dev/sssom-py/sssom/util.py", line 11, in <module>
    from sssom.datamodel_util import MappingSetDiff, EntityPair
  File "/Users/cthoyt/dev/sssom-py/sssom/datamodel_util.py", line 5, in <module>
    from sssom.sssom_document import MappingSetDocument
  File "/Users/cthoyt/dev/sssom-py/sssom/sssom_document.py", line 1, in <module>
    from .sssom_datamodel import MappingSet, Mapping, Entity
  File "/Users/cthoyt/dev/sssom-py/sssom/sssom_datamodel.py", line 16, in <module>
    from linkml.utils.slot import Slot
ModuleNotFoundError: No module named 'linkml.utils.slot'
```

I think `sssom validate` can accept a URL, so you could also do this to verify:

```shell
$ sssom validate https://github.com/biomappings/biomappings/raw/add-sssom-export/docs/_data/biomappings.sssom.tsv
```

**Comment by matentzn** [comment] 2021-06-25 08:35
How did you install sssom?

**Comment by cthoyt** [comment] 2021-06-25 12:58
I installed from source with pip install -e .  But when I ran it it was missing linkml_model and linkml so I pip installed both of those too

**Comment by cthoyt** [comment] 2021-07-20 18:47
@joeflack4 good call. hopefully the version information can get bumped and we can add a unit test to make sure this is always the case

**Comment by matentzn** [comment] 2021-08-31 10:03
This should be fixed now, let me know if there are still issues!

**Closed by matentzn** 2021-08-31 10:03 UTC

**Comment by cthoyt** [comment] 2021-08-31 10:13
@matentzn was there specific code that fixed this? It would be nice if it had referenced the issue


Will be able to check if this is resolved after the packaging PR is merged.

**Comment by matentzn** [comment] 2021-08-31 12:25
The error was caused by a conflict in linkml version - at least it looks like the one I had, and mine was fixed with the upgrade to the latest linkml dependencies.. It was a while back, some change to requirements.txt that then moved to steup.cfg.
