### ISSUE TITLE
owl conversion: sssom:superclass_of should be inverted and turned into an OWL subClassOf axiom

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom-py#17] opened 2021-02-22 04:46 UTC
Given an sssom triple A superclass_of B, this should be turned into B SubClassOf A

@matentzn : we may have prematurely replaced the hacky but functional perl code I had in the COB repo...

**Comment by matentzn** [comment] 2021-02-22 11:56
I cant confirm this - if you run `test_from_tsv` in test_conversion.py you will see all the superclass statements translated into subclass of axioms.. Could this be due to the fact that I forgot to [adjust the COB Makefile](https://github.com/OBOFoundry/COB/pull/153)?

In any case, the swapping logic is here:
https://github.com/mapping-commons/sssom-py/blob/e8ed9522409edb4d28e9ed9e23261c81db889686/sssom/parsers.py#L243

If there is something not working for you, I would need a reproducible example :)

**Comment by matentzn** [comment] 2021-03-10 14:56
Closing for now but feel free to reopen!

**Closed by matentzn** 2021-03-10 14:56 UTC
